using CRial.Python;
using System;

namespace CRial.xbmcgui
{
    public class ActionEventArgs : EventArgs
    {
        public ActionId Id;
        //
        public ActionEventArgs(ActionId id)
        {
            Id = id;
        }
    }
    public class Action : PythonObject
    {
        public Action() : base("")
        {
            _name = "self.act_" + Utils.GenerateId();
            Utils.Call(_name + " = xbmcgui.Action()");
        }
        internal Action(string name) : base(name)
        {
            _name = name;
        }
        //
        public int getAmount1()
        {
            return Utils.Call<int>(_name + ".getAmount1()");
        }
        public int getAmount2()
        {
            return Utils.Call<int>(_name + ".getAmount2()");
        }
        public int getButtonCode()
        {
            return Utils.Call<int>(_name + ".getButtonCode()");
        }
        public ActionId getId()
        {
            return (ActionId)Utils.Call<int>(_name + ".getId()");
        }
    }
    public enum ActionId : int
    {
        NONE = 0,
        MOVE_LEFT = 1,
        MOVE_RIGHT = 2,
        MOVE_UP = 3,
        MOVE_DOWN = 4,
        PAGE_UP = 5,
        PAGE_DOWN = 6,
        SELECT_ITEM = 7,
        HIGHLIGHT_ITEM = 8,
        PARENT_DIR = 9,
        PREVIOUS_MENU = 10,
        SHOW_INFO = 11,
        PAUSE = 12,
        STOP = 13,
        NEXT_ITEM = 14,
        PREV_ITEM = 15,
        FORWARD = 16,//!<Canbeusedtospecifyspecificactioninawindow,PlaybackcontrolishandledinACTION_PLAYER_*,
        REWIND = 17,//!<Canbeusedtospecifyspecificactioninawindow,PlaybackcontrolishandledinACTION_PLAYER_*,
        SHOW_GUI = 18,//!<togglebetweenGUIandmovieorGUIandvisualisation.,
        ASPECT_RATIO = 19,//!<togglequick-accesszoommodes.CanbusedinvideoFullScreen.zmlwindowid=2005,
        STEP_FORWARD = 20,//!<seek+1%inthemovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        STEP_BACK = 21,//!<seek-1%inthemovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        BIG_STEP_FORWARD = 22,//!<seek+10%inthemovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        BIG_STEP_BACK = 23,//!<seek-10%inthemovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        SHOW_OSD = 24,//!<show/hideOSD.CanbusedinvideoFullScreen.xmlwindowid=2005,
        SHOW_SUBTITLES = 25,//!<turnsubtitleson/off.CanbusedinvideoFullScreen.xmlwindowid=2005,
        NEXT_SUBTITLE = 26,//!<switchtonextsubtitleofmovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        BROWSE_SUBTITLE = 247,//!<Browseforsubtitle.Canbeusedinvideofullscreen,
        PLAYER_DEBUG = 27,//!<showdebuginfoforVideoPlayer,
        NEXT_PICTURE = 28,//!<shownextpictureofslideshow.Canbusedinslideshow.xmlwindowid=2007,
        PREV_PICTURE = 29,//!<showpreviouspictureofslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_OUT = 30,//!<zoominpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_IN = 31,//!<zoomoutpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        TOGGLE_SOURCE_DEST = 32,//!<usedtotogglebetweensourceviewanddestinationview.Canbeusedinmyfiles.xmlwindowid=3,
        SHOW_PLAYLIST = 33,//!<usedtotogglebetweencurrentviewandplaylistview.Canbusedinallmymusicxmlfiles,
        QUEUE_ITEM = 34,//!<usedtoqueueaitemtotheplaylist.Canbusedinallmymusicxmlfiles,
        REMOVE_ITEM = 35,//!<notusedanymore,
        SHOW_FULLSCREEN = 36,//!<notusedanymore,
        ZOOM_LEVEL_NORMAL = 37,//!<zoom1xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_1 = 38,//!<zoom2xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_2 = 39,//!<zoom3xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_3 = 40,//!<zoom4xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_4 = 41,//!<zoom5xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_5 = 42,//!<zoom6xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_6 = 43,//!<zoom7xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_7 = 44,//!<zoom8xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_8 = 45,//!<zoom9xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        ZOOM_LEVEL_9 = 46,//!<zoom10xpictureduringslideshow.Canbusedinslideshow.xmlwindowid=2007,
        CALIBRATE_SWAP_ARROWS = 47,//!<selectnextarrow.Canbusedin:settingsScreenCalibration.xmlwindowid=11,
        CALIBRATE_RESET = 48,//!<resetcalibrationtodefaults.Canbusedin:`settingsScreenCalibration.xml`windowid=11/settingsUICalibration.xmlwindowid=10,
        ANALOG_MOVE = 49,//!<analogthumbstickmove.Canbusedin:`slideshow.xml`windowid=2007/settingsScreenCalibration.xmlwindowid=11/settingsUICalibration.xmlwindowid=10,//!<@noteseealsoACTION_ANALOG_MOVE_X_LEFT,ACTION_ANALOG_MOVE_X_RIGHT,ACTION_ANALOG_MOVE_Y_UP,ACTION_ANALOG_MOVE_Y_DOWN,
        ROTATE_PICTURE_CW = 50,//!<rotatecurrentpictureclockwiseduringslideshow.Canbeusedinslideshow.xmlwindowid=2007,
        ROTATE_PICTURE_CCW = 51,//!<rotatecurrentpicturecounterclockwiseduringslideshow.Canbeusedinslideshow.xmlwindowid=2007,
        SUBTITLE_DELAY_MIN = 52,//!<Decreasesubtitle/movieDelay.CanbusedinvideoFullScreen.xmlwindowid=2005,
        SUBTITLE_DELAY_PLUS = 53,//!<Increasesubtitle/movieDelay.CanbusedinvideoFullScreen.xmlwindowid=2005,
        AUDIO_DELAY_MIN = 54,//!<Increaseavsyncdelay.CanbusedinvideoFullScreen.xmlwindowid=2005,
        AUDIO_DELAY_PLUS = 55,//!<Decreaseavsyncdelay.CanbusedinvideoFullScreen.xmlwindowid=2005,
        AUDIO_NEXT_LANGUAGE = 56,//!<Selectnextlanguageinmovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        CHANGE_RESOLUTION = 57,//!<switch2nextresolution.CanbusedduringscreencalibrationsettingsScreenCalibration.xmlwindowid=11,
        REMOTE_0 = 58,//!<remotekeys0-9.areusedbymultiplewindows,
        REMOTE_1 = 59,//!<forexampleinvideoFullScreen.xmlwindowid=2005youcan,
        REMOTE_2 = 60,//!<entertime(mmss)tojumptoparticularpointinthemovie,
        REMOTE_3 = 61,
        REMOTE_4 = 62,//!<withspincontrolsyoucanenter3digitnumbertoquicklyset,
        REMOTE_5 = 63,//!<spincontroltodesiredvalue,
        REMOTE_6 = 64,
        REMOTE_7 = 65,
        REMOTE_8 = 66,
        REMOTE_9 = 67,
        PLAYER_PROCESS_INFO = 69,//!<showplayerprocessinfo(videodecoder,pixelformat,pvrsignalstrengthandthelike,
        PLAYER_PROGRAM_SELECT = 70,
        SMALL_STEP_BACK = 76,//!<jumpsafewsecondsbackduringplaybackofmovie.CanbusedinvideoFullScreen.xmlwindowid=2005,
        PLAYER_FORWARD = 77,//!<FFincurrentfileplayed.globalaction,canbeusedanywhere,
        PLAYER_REWIND = 78,//!<RWincurrentfileplayed.globalaction,canbeusedanywhere,
        PLAYER_PLAY = 79,//!<Playcurrentsong.Unpausessongandsetsplayspeedto1x.globalaction,canbeusedanywhere,
        DELETE_ITEM = 80,//!<deletecurrentselecteditem.Canbeusedinmyfiles.xmlwindowid=3andinmyvideoTitle.xmlwindowid=25,
        COPY_ITEM = 81,//!<copycurrentselecteditem.Canbeusedinmyfiles.xmlwindowid=3,
        MOVE_ITEM = 82,//!<movecurrentselecteditem.Canbeusedinmyfiles.xmlwindowid=3,
        TAKE_SCREENSHOT = 85,//!<takeascreenshot,
        RENAME_ITEM = 87,//!<renameitem,
        VOLUME_UP = 88,
        VOLUME_DOWN = 89,
        VOLAMP = 90,
        MUTE = 91,
        NAV_BACK = 92,
        VOLAMP_UP = 93,
        VOLAMP_DOWN = 94,
        CREATE_EPISODE_BOOKMARK = 95,//!<Createsanepisodebookmarkonthecurrentlyplayingvideofilecontainingmorethanoneepisode,
        CREATE_BOOKMARK = 96,//!<Createsabookmarkofthecurrentlyplayingvideofile,
        CHAPTER_OR_BIG_STEP_FORWARD = 97,//!<Gotothenextchapter,ifnotavailableperformabigstepforward,
        CHAPTER_OR_BIG_STEP_BACK = 98,//!<Gotothepreviouschapter,ifnotavailableperformabigstepback,
        CYCLE_SUBTITLE = 99,//!<switchtonextsubtitleofmovie,butwillnotenable/disablethesubtitles.CanbeusedinvideoFullScreen.xmlwindowid=2005,
        MOUSE_START = 100,
        MOUSE_LEFT_CLICK = 100,
        MOUSE_RIGHT_CLICK = 101,
        MOUSE_MIDDLE_CLICK = 102,
        MOUSE_DOUBLE_CLICK = 103,
        MOUSE_WHEEL_UP = 104,
        MOUSE_WHEEL_DOWN = 105,
        MOUSE_DRAG = 106,
        MOUSE_MOVE = 107,
        MOUSE_LONG_CLICK = 108,
        MOUSE_END = 109,
        BACKSPACE = 110,
        SCROLL_UP = 111,
        SCROLL_DOWN = 112,
        ANALOG_FORWARD = 113,
        ANALOG_REWIND = 114,
        MOVE_ITEM_UP = 115,//!<moveitemupinplaylist,
        MOVE_ITEM_DOWN = 116,//!<moveitemdowninplaylist,
        CONTEXT_MENU = 117,//!<popsupthecontextmenu,
        SHIFT = 118,//!<stuffforvirtualkeyboardshortcuts,
        SYMBOLS = 119,//!<stuffforvirtualkeyboardshortcuts,
        CURSOR_LEFT = 120,//!<stuffforvirtualkeyboardshortcuts,
        CURSOR_RIGHT = 121,//!<stuffforvirtualkeyboardshortcuts,
        BUILT_IN_FUNCTION = 122,
        SHOW_OSD_TIME = 123,//!<displayscurrenttime,canbeusedinvideoFullScreen.xmlwindowid=2005,
        ANALOG_SEEK_FORWARD = 124,//!<seeksforward,anddisplaystheseekbar.,
        ANALOG_SEEK_BACK = 125,//!<seeksbackward,anddisplaystheseekbar.,
        VIS_PRESET_SHOW = 126,
        VIS_PRESET_NEXT = 128,
        VIS_PRESET_PREV = 129,
        VIS_PRESET_LOCK = 130,
        VIS_PRESET_RANDOM = 131,
        VIS_RATE_PRESET_PLUS = 132,
        VIS_RATE_PRESET_MINUS = 133,
        SHOW_VIDEOMENU = 134,
        ENTER = 135,
        INCREASE_RATING = 136,
        DECREASE_RATING = 137,
        NEXT_SCENE = 138,//!<switchtonextscene/cutpointinmovie,
        PREV_SCENE = 139,//!<switchtopreviousscene/cutpointinmovie,
        NEXT_LETTER = 140,//!<jumpthroughalistorcontainerbyletter,
        PREV_LETTER = 141,
        JUMP_SMS2 = 142,//!<jumpdirecttoaparticularletterusingSMS-styleinput,
        JUMP_SMS3 = 143,
        JUMP_SMS4 = 144,
        JUMP_SMS5 = 145,
        JUMP_SMS6 = 146,
        JUMP_SMS7 = 147,
        JUMP_SMS8 = 148,
        JUMP_SMS9 = 149,
        FILTER_CLEAR = 150,
        FILTER_SMS2 = 151,
        FILTER_SMS3 = 152,
        FILTER_SMS4 = 153,
        FILTER_SMS5 = 154,
        FILTER_SMS6 = 155,
        FILTER_SMS7 = 156,
        FILTER_SMS8 = 157,
        FILTER_SMS9 = 158,
        FIRST_PAGE = 159,
        LAST_PAGE = 160,
        AUDIO_DELAY = 161,
        SUBTITLE_DELAY = 162,
        MENU = 163,
        SET_RATING = 164,
        RECORD = 170,
        PASTE = 180,
        NEXT_CONTROL = 181,
        PREV_CONTROL = 182,
        CHANNEL_SWITCH = 183,
        CHANNEL_UP = 184,
        CHANNEL_DOWN = 185,
        NEXT_CHANNELGROUP = 186,
        PREVIOUS_CHANNELGROUP = 187,
        PVR_PLAY = 188,
        PVR_PLAY_TV = 189,
        PVR_PLAY_RADIO = 190,
        PVR_SHOW_TIMER_RULE = 191,
        CHANNEL_NUMBER_SEP = 192,
        TOGGLE_FULLSCREEN = 199,//!<switch2desktopresolution,
        TOGGLE_WATCHED = 200,//!<Togglewatchedstatus(videos),
        SCAN_ITEM = 201,//!<scanitem,
        TOGGLE_DIGITAL_ANALOG = 202,//!<switchdigital<->analog,
        RELOAD_KEYMAPS = 203,//!<reloadsCButtonTranslator'skeymaps,
        GUIPROFILE_BEGIN = 204,//!<starttheGUIControlProfilerrunning,
        TELETEXT_RED = 215,//!<TeletextColorbutton<b>Red</b>tocontrolTopText,
        TELETEXT_GREEN = 216,//!<TeletextColorbutton<b>Green</b>tocontrolTopText,
        TELETEXT_YELLOW = 217,//!<TeletextColorbutton<b>Yellow</b>tocontrolTopText,
        TELETEXT_BLUE = 218,//!<TeletextColorbutton<b>Blue</b>tocontrolTopText,
        INCREASE_PAR = 219,
        DECREASE_PAR = 220,
        VSHIFT_UP = 227,//!<shiftupvideoimageinVideoPlayer,
        VSHIFT_DOWN = 228,//!<shiftdownvideoimageinVideoPlayer,
        PLAYER_PLAYPAUSE = 229,//!<Play/pause.Ifplayingitpauses,ifpauseditplays.,
        SUBTITLE_VSHIFT_UP = 230,//!<shiftupsubtitlesinVideoPlayer,
        SUBTITLE_VSHIFT_DOWN = 231,//!<shiftdownsubtitlesinVideoPlayer,
        SUBTITLE_ALIGN = 232,//!<toggleverticalalignmentofsubtitles,
        FILTER = 233,
        SWITCH_PLAYER = 234,
        STEREOMODE_NEXT = 235,
        STEREOMODE_PREVIOUS = 236,
        STEREOMODE_TOGGLE = 237,//!<turns3dmodeon/off,
        STEREOMODE_SELECT = 238,
        STEREOMODE_TOMONO = 239,
        STEREOMODE_SET = 240,
        SETTINGS_RESET = 241,
        SETTINGS_LEVEL_CHANGE = 242,
        TRIGGER_OSD = 243,//!<showautoclosingOSD.CanbusedinvideoFullScreen.xmlwindowid=2005,
        INPUT_TEXT = 244,
        VOLUME_SET = 245,
        TOGGLE_COMMSKIP = 246,
        PLAYER_RESET = 248,//!<Sendaresetcommandtotheactivegame,
        TOGGLE_FONT = 249,//!<Togglefont.UsedinTextViewerdialog,
        VOICE_RECOGNIZE = 300,
        TOUCH_TAP = 401,//!<touchactions,
        TOUCH_TAP_TEN = 410,//!<touchactions,
        TOUCH_LONGPRESS = 411,//!<touchactions,
        TOUCH_LONGPRESS_TEN = 420,//!<touchactions,
        GESTURE_NOTIFY = 500,
        GESTURE_BEGIN = 501,
        GESTURE_ZOOM = 502,//!<sendactionwithpointandcurrentPinchScale(fingerstogether<1.0->fingersapart>1.0),
        GESTURE_ROTATE = 503,
        GESTURE_PAN = 504,
        GESTURE_ABORT = 505,
        GESTURE_SWIPE_LEFT = 511,
        GESTURE_SWIPE_LEFT_TEN = 520,
        GESTURE_SWIPE_RIGHT = 521,
        GESTURE_SWIPE_RIGHT_TEN = 530,
        GESTURE_SWIPE_UP = 531,
        GESTURE_SWIPE_UP_TEN = 540,
        GESTURE_SWIPE_DOWN = 541,
        GESTURE_SWIPE_DOWN_TEN = 550,
        GESTURE_END = 599,
        ANALOG_MOVE_X_LEFT = 601,//!<analogthumbstickmove,horizontalaxis,left;seeACTION_ANALOG_MOVE,
        ANALOG_MOVE_X_RIGHT = 602,//!<analogthumbstickmove,horizontalaxis,right;seeACTION_ANALOG_MOVE,
        ANALOG_MOVE_Y_UP = 603,//!<analogthumbstickmove,verticalaxis,up;seeACTION_ANALOG_MOVE,
        ANALOG_MOVE_Y_DOWN = 604,//!<analogthumbstickmove,verticalaxis,down;seeACTION_ANALOG_MOVE,
        ERROR = 998,
        NOOP = 999,
    }
}